# first Nootebook for Pandas and Data Visualization

## Pandas Pacakage modules

In [2]:
import pandas as pd

In [63]:
df = pd.read_csv("data.csv")
df.head()

     Gene  Sample1  Sample2  Sample3  Length
0   Gene1      7.2      6.8      7.5  1000.0
1   Gene2      5.1      4.9      5.3   800.0
2   Gene3      6.8      7.0      6.5  1200.0
3   Gene4      4.5      4.7      4.3   900.0
4   Gene5      6.2      6.0      6.4  1100.0

In [ ]:
# df.info() # for getting data info 
#df.describe() # for getting the statistical summary of the data
# df.shape # for getting the number of rows and columns in the data
# df.index  # for getting the index of the data

RangeIndex(start=0, stop=50, step=1)

In [11]:
df['Gene'].dtype

dtype('O')

In [13]:
S1_mean=df['Sample1'].mean()
S1_mean

np.float64(5.912000000000001)

In [22]:
d=df['Sample1'].sort_index()
d.head()

0    7.2
1    5.1
2    6.8
3    4.5
4    6.2
Name: Sample1, dtype: float64

In [20]:
df['Sample1'].min()

np.float64(4.5)

In [23]:
df.isnull().sum()

Gene       0
Sample1    0
Sample2    2
Sample3    1
Length     1
dtype: int64

In [66]:
df.fillna('mean',inplace=True)
df

       Gene  Sample1 Sample2 Sample3  Length
0     Gene1      7.2     6.8     7.5  1000.0
1     Gene2      5.1     4.9     5.3   800.0
2     Gene3      6.8     7.0     6.5  1200.0
3     Gene4      4.5     4.7     4.3   900.0
4     Gene5      6.2     6.0     6.4  1100.0
5     Gene6      5.8     5.9     5.7   950.0
6     Gene7      7.0     6.9     7.1  1050.0
7     Gene8      4.8     4.6     4.9   850.0
8     Gene9      6.5     6.7     6.4  1150.0
9    Gene10      5.0     5.2     5.1   900.0
10   Gene11      7.3     7.1     7.4  1020.0
11   Gene12      4.9     5.0     4.8   880.0
12   Gene13      6.6     6.5     6.7  1080.0
13   Gene14      5.2     5.3     5.1   920.0
14   Gene15      6.9     7.0     6.8  1120.0
15   Gene16      4.7     4.8     4.6   860.0
16   Gene17      6.4     6.3     6.5  1070.0
17   Gene18      5.3     5.4     5.2   930.0
18   Gene19      7.1     6.9     7.2  1040.0
19   Gene20      4.6     4.5     4.7   870.0
20   Gene21      6.7     6.8     6.6  1090.0
21   Gene22      5.1     5.0     5.2   910.0
22   Gene23      7.0     7.1     6.9  1060.0
23   Gene24      4.8     4.9     4.7   890.0
24   Gene25      6.5     6.4     6.6  1110.0
25   Gene26      5.4     5.5     5.3   940.0
26   Gene27      6.8     6.7     6.9  1030.0
27   Gene28      4.9     4.8     5.0   880.0
28   Gene29      7.2     7.3     7.1  1080.0
29   Gene30      5.0     5.1     4.9   900.0
30   Gene31      6.6     6.5     6.7  1100.0
31   Gene32      5.2     5.3     5.1   920.0
32   Gene33      6.9     7.0     6.8  1050.0
33   Gene34      4.7    mean     4.8   870.0
34   Gene35      6.4     6.5     6.3  1070.0
35   Gene36      5.3     5.2     5.4   930.0
36   Gene37      7.1     7.0     7.2  1040.0
37   Gene38      4.8     4.9     4.7   890.0
38   Gene39      6.7     6.6    mean  1090.0
39   Gene40      5.1     5.0     5.2   910.0
40   Gene41      7.0     7.1     6.9  1060.0
41   Gene42      4.9     5.0     4.8    mean
42   Gene43      6.5     6.4     6.6  1110.0
43   Gene44      5.4     5.5     5.3   940.0
44   Gene45      6.8     6.7     6.9  1030.0
45   Gene46      4.9     4.8     5.0   880.0
46   Gene47      7.2    mean     7.1  1080.0
47   Gene48      5.0     5.1     4.9   900.0
48   Gene49      6.6     6.5     6.7  1100.0
49   Gene50      5.2     5.3     5.1   920.0

In [77]:
def filter(df,threshold):
    df['mean']=df[['Sample1','Sample2','Sample3']].mean(axis=1)
    return df[df['mean']<threshold][['Gene','mean']]

df=pd.read_csv('data.csv')
results=filter(df,5)
results

       Gene      mean
3     Gene4  4.500000
7     Gene8  4.766667
11   Gene12  4.900000
15   Gene16  4.700000
19   Gene20  4.600000
23   Gene24  4.800000
27   Gene28  4.900000
33   Gene34  4.750000
37   Gene38  4.800000
41   Gene42  4.900000
45   Gene46  4.900000